import typescriptConfig from '@playcanvas/eslint-config/typescript';
import globals from 'globals';

export default [
    ...typescriptConfig,
    {
        files: ['**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.browser
            }
        }
    },
    {
        files: ['**/*.mjs'],
        languageOptions: {
            globals: {
                ...globals.node
            }
        }
    },
    {
        // Preserve existing module initialization order and the Metaflow
        // analytics/config bootstrap sequence.
        files: [
            'src/cameras/anim-controller.ts',
            'src/cameras/fly-controller.ts',
            'src/cameras/walk-controller.ts',
            'src/index.ts'
        ],
        rules: {
            'import-x/order': 'off'
        }
    },
    {
        // Metaflow's collision, shader, browser-input, and legacy settings
        // boundaries intentionally accept dynamically shaped values. Narrowing
        // those contracts belongs in behavior-specific changes, not this
        // mechanical upstream toolchain alignment.
        files: [
            'src/annotations.ts',
            'src/collision/mesh-collision.ts',
            'src/core/observe.ts',
            'src/gsplat-reveal-radial.ts',
            'src/index.ts',
            'src/input/app/pointer-lock.ts',
            'src/input/devices/keyboard-mouse.ts',
            'src/module/settings.d.ts',
            'src/schemas/v2.ts',
            'src/settings.ts',
            'src/tooltip.ts',
            'src/viewer.ts'
        ],
        rules: {
            '@typescript-eslint/no-explicit-any': 'off'
        }
    },
    {
        // flipXY is an intentionally polymorphic compatibility getter for the
        // legacy Metaflow Rz180 coordinate adapter.
        files: ['src/collision/voxel-collision.ts'],
        rules: {
            '@typescript-eslint/class-literal-property-style': 'off'
        }
    },
    {
        // Imports are generated by the package build.
        files: ['src/module/index.ts'],
        rules: {
            'import-x/no-unresolved': 'off'
        }
    }
];
