import typescriptConfig from '@playcanvas/eslint-config/typescript';
import globals from 'globals';

export default [
    ...typescriptConfig,
    {
        files: ['**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.browser
            }
        }
    },
    {
        files: ['**/*.mjs'],
        languageOptions: {
            globals: {
                ...globals.node
            }
        }
    },
    {
        // Preserve existing module initialization order and the Metaflow
        // analytics/config bootstrap sequence.
        files: [
            'src/cameras/anim-controller.ts',
            'src/cameras/fly-controller.ts',
            'src/cameras/walk-controller.ts',
            'src/index.ts'
        ],
        rules: {
            'import-x/order': 'off'
        }
    },
    {
        // Imports are generated by the package build.
        files: ['src/module/index.ts'],
        rules: {
            'import-x/no-unresolved': 'off'
        }
    }
];
